nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

# Enable zero-installs for faster CI/CD
enableScripts: true

# Configure network settings
network-timeout: 100000

# Configure package resolution
resolutionMode: highest

# Configure package checksums
checksumBehavior: update

# Configure package registry
npmRegistryServer: "https://registry.npmjs.org/"

# Configure package access
npmAlwaysAuth: false

# Configure package scope
npmScope: ""

# Configure package publish
npmPublishRegistry: "https://registry.npmjs.org/"
npmPublishAccess: "public"

# Configure package cache
cacheFolder: "./.yarn/cache"

# Configure package offline mode
offline: false

# Configure package network concurrency
networkConcurrency: 8

# Configure package progress
progress: true

# Configure package verbose
verbose: false

# Configure package no-progress
noProgress: false

# Configure package no-emoji
noEmoji: false

# Configure package no-lockfile
noLockfile: false

# Configure package no-manifest
noManifest: false

# Configure package no-node-version-check
noNodeVersionCheck: false

# Configure package no-plugins
noPlugins: false

# Configure package no-progress
noProgress: false

# Configure package no-verify-store-integrity
noVerifyStoreIntegrity: false

# Configure package prefer-offline
preferOffline: false

# Configure package prefer-https
preferHttps: true

# Configure package production
production: false

# Configure package registry
registry: "https://registry.npmjs.org/"

# Configure package save-prefix
savePrefix: "^"

# Configure package save-exact
saveExact: false

# Configure package scripts-prepend-node-path
scriptsPrependNodePath: false

# Configure package user-agent
userAgent: "yarn/1.22.22 npm/? node/v18.0.0 darwin x64"

# Configure package version
version: "1.22.22"

# Configure package workspaces
workspaces: true 